<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
    'Success' => '操作成功',
    'System Error!' => '系统错误',
    'Response Type Error' => '返回类型有误',
    'The parameters of request is not enough or error' => '参数错误',
    'Authentication failed!' => '参数验证不通过',
    'illegal operation' => '非法操作',

    'Empty phone' => '手机号不能为空',
    'Phone has exists' => '手机号已经存在',
    'The format of the phone is illegal' => '手机号格式不正确',
    'The password is empty' => '密码不能为空',
    'The format of the password is illegal' => '密码格式不正确',
);
