<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'bind email' => '绑定邮箱',
  'change email' => '更改邮箱',
    'active email' => '激活邮箱',
    'bind phone' => '绑定手机',
    'change phone' => '更改手机',
    'active phone' => '激活手机',
    'bind password' => '设置密码',
    'change password' => '修改密码',
  'reset password email' => '重置密码',
  'verify email success' => '绑定邮箱成功',
  'verity email' => '绑定验证邮箱',
);
