<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Activate' => '',
  'BBS' => '',
  'Email Binded' => '已绑定',
  'Email Not Bind' => '未绑定',
    'Email Not Active' => '未激活',
    'Phone Binded' => '已绑定',
    'Phone Not Bind' => '未绑定',
    'Phone Not Active' => '未激活',
    'Password Binded' => '已设置',
    'Password Not Bind' => '未设置',
  'Enter the activation code you received below.' => '',
  'Gonglue' => '',
  'If you failed to recieve the activation email, click the Resend Activation button.' => '',
  'Manage' => '',
  'Manage users' => '',
  'Other' => '',
  'Password Not Set' => '',
  'Password Reseting' => '',
  'Password Seted' => '',
  'Profile' => '',
  'Profile of ' => '',
  'Resend Activation' => '',
  'User Active' => '',
  'User Forbidden' => '',
  'User Not Active' => '',
  'User list' => '',
  'Users' => '',
  'WanYou' => '',
  'Website' => '',
  'Zhushou' => '',
  'female' => '',
  'male' => '',
  'none' => '',
  'zone china cn' => '',
  'zone china taiwan' => '',
);
