<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'appid' => '',
  'authorise error' => '授权错误',
  'avatar' => '头像',
  'avatar too large' => '头像大小太大',
  'avatar wrong type' => '头像图片类型错误',
  'coin' => '魔币',
  'crypt' => '重要参数',
  'diamond' => '魔钻',
  'gender' => '性别',
  'ip' => 'IP',
  'md5Password' => '密码',
  'must input {email} or {phone}' => '必须填写{email}或者{phone}',
  'must input {email} or {phone} or {username}' => '必须填写{email}或者{phone}或者{username}',
  'newPassword' => '新密码',
  'nickname' => '昵称',
  'oldEmail' => '原邮箱',
  'oldPassword' => '原密码',
  'phone_vcode' => '手机验证码',
  'rawPassword' => '密码',
  'request_id' => 'id',
  'sex' => '性别',
  'sign' => '签名',
  'sign error' => '签名错误',
  'the length of {attribute} is illegal, current length is {length},maximal length is {max}, minimal length is {min}' => '{attribute}最大长度为{max},最小长度为{min},当前长度为{length}',
  'uid' => '用户ID',
  'user' => '用户',
  'wanyou_flag' => '同步类型',
  'wanyou_id' => '万游ID',
  'your ip is limit' => '登陆错误次数太多，请稍后再试',
  'register your ip is limit' => '登您的IP已达到单位时间注册次数限制，请稍后再试',
  '{attribute} contains sensitive word' => '{attribute}包含敏感词汇',
  'password' => '登录密码',
  'the length of {attribute} is illegal, maximal length is {max}, minimal length is {min}' => '{attribute}最大长度为{max},最小长度为{min}',
  'your ip sign in too often' => '您的IP已达到单位时间注册次数限制，请稍后再试',
  '{attribute} is illegal' => '{attribute}格式不正确',
  'email' => '电子邮箱',
  'phone' => '手机号码',
  'request type' => '请求来源',
  'username' => '用户名',
  'vcode' => '验证码',
  '{attribute} has exist.' => '{attribute}已经存在',
  'Lack of necessary parameter' => '缺少必要参数',
  'Please input the Phone Captcha' => '请输入手机验证码',
  'The Captcha has expired or wrong' => '验证码错误或已经过期',
    'Please input the Email Captcha' => '请输入邮箱验证码',
    'url is error' => '链接错误',
    'register expiry' => '注册链接超时，请重新注册',
);
